version: '3.1'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    # volumes:
    #   - ./data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: on-failure
  nginx:
    build: requirements/nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/wordpress
    ports:
      - 443:443
    restart: always
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge

volumes:
  mariadb-data:
  wordpress-data:
