version: '3.1'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_ROOT_USER: ${DB_ROOT_USER}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - inception
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
  nginx:
    build: requirements/nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - ./data/nginx:/var/www/html
    ports:
      - 443:443
    restart: always

networks:
  inception:
    driver: bridge
