version: '3.1'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: on-failure
  nginx:
    build: requirements/nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/wordpress
    ports:
      - 443:443
    restart: always
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
  redis:
    build: bonus/redis/
    container_name: redis
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      device: ${VPATH}/mariadb
      o: bind
      type: none
  wordpress-data:
    driver: local
    driver_opts:
      device: ${VPATH}/wordpress
      o: bind
      type: none
